import { useState, useEffect, useMemo } from 'react';
import { alertApi, stationApi, trainApi } from '../services/api';
import { Bell, CheckCheck, Filter } from 'lucide-react';
import { cn, getSeverityBg } from '../utils/helpers';
import { SectionHeader } from '../components/ui/SectionHeader';
import { EmptyState } from '../components/ui/EmptyState';
import type { Alert, AlertSeverity, Station, Train } from '../types';
import toast from 'react-hot-toast';

export default function AlertCenter() {
  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [stations, setStations] = useState<Record<number, Station>>({});
  const [trains, setTrains] = useState<Record<number, Train>>({});
  const [filter, setFilter] = useState<'ALL' | AlertSeverity>('ALL');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let mounted = true;
    (async () => {
      try {
        const [alertRes, stationRes, trainRes] = await Promise.all([
          alertApi.list({ active_only: true }),
          stationApi.list({ page_size: 100 }).catch(() => null),
          trainApi.list({ page_size: 100 }).catch(() => null),
        ]);
        if (!mounted) return;
        setAlerts(alertRes.data);
        const sMap: Record<number, Station> = {};
        const rawStations = stationRes?.data as unknown;
        const stationList = Array.isArray(rawStations) ? rawStations : (rawStations as { items?: Station[] } | undefined)?.items ?? [];
        stationList.forEach((s: Station) => { sMap[s.id] = s; });
        const tMap: Record<number, Train> = {};
        (trainRes?.data?.trains || []).forEach((t) => { tMap[t.id] = t; });
        setStations(sMap);
        setTrains(tMap);
      } finally {
        if (mounted) setLoading(false);
      }
    })();
    return () => { mounted = false; };
  }, []);

  const filtered = useMemo(() => {
    const list = filter === 'ALL' ? alerts : alerts.filter((a) => a.severity === filter);
    const order: Record<AlertSeverity, number> = { CRITICAL: 0, WARNING: 1, INFO: 2 };
    return [...list].sort((a, b) => (order[a.severity] ?? 3) - (order[b.severity] ?? 3) || new Date(b.created_at).getTime() - new Date(a.created_at).getTime());
  }, [alerts, filter]);

  const acknowledge = async (id: number) => {
    try {
      await alertApi.acknowledge(id);
      setAlerts((prev) => prev.map((a) => (a.id === id ? { ...a, is_acknowledged: true } : a)));
      toast.success('Alert acknowledged');
    } catch {
      toast.error('Failed to acknowledge');
    }
  };

  const filters: ('ALL' | AlertSeverity)[] = ['ALL', 'CRITICAL', 'WARNING', 'INFO'];

  return (
    <div className="space-y-6">
      <SectionHeader
        title="Operations Alert Center"
        subtitle="Live alerts generated by the intelligence engine"
        right={
          <div className="flex items-center gap-1">
            <Filter className="h-4 w-4 text-gray-500" />
            {filters.map((f) => (
              <button key={f} onClick={() => setFilter(f)}
                className={cn('px-2.5 py-1 rounded-md text-xs font-medium transition-colors',
                  filter === f ? 'bg-accent/15 text-accent border border-accent/30' : 'text-gray-400 hover:text-gray-200 border border-transparent')}>
                {f === 'ALL' ? 'All' : f.charAt(0) + f.slice(1).toLowerCase()}
              </button>
            ))}
          </div>
        }
      />

      {loading ? (
        <div className="space-y-2">
          {Array.from({ length: 5 }).map((_, i) => <div key={i} className="animate-pulse rounded-xl bg-white/[0.05] h-20" />)}
        </div>
      ) : filtered.length === 0 ? (
        <div className="card"><EmptyState icon={Bell} title="No alerts" message="No alerts match the current filter." /></div>
      ) : (
        <div className="space-y-2">
          {filtered.map((a) => (
            <div key={a.id} className={cn('card p-4 flex items-start gap-3 animate-fade-in', a.severity === 'CRITICAL' && 'border-rail-red/25')}>
              <span className={cn('w-2 h-2 rounded-full mt-1.5 shrink-0', a.severity === 'CRITICAL' ? 'bg-rail-red shadow-glow-red animate-pulse-slow' : a.severity === 'WARNING' ? 'bg-rail-amber' : 'bg-rail-blue')} />
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 flex-wrap">
                  <span className={cn(getSeverityBg(a.severity))}>{a.severity}</span>
                  <span className="badge-info">{a.alert_type.replace(/_/g, ' ')}</span>
                  {a.train_id && <span className="badge-neutral">Train {trains[a.train_id]?.train_number || `#${a.train_id}`}</span>}
                  {a.station_id && <span className="badge-neutral">{stations[a.station_id]?.code || `Stn #${a.station_id}`}</span>}
                  {a.is_acknowledged && <span className="badge-success">Acknowledged</span>}
                </div>
                <h3 className="text-sm font-semibold text-gray-100 mt-1.5">{a.title}</h3>
                <p className="text-sm text-gray-500 mt-0.5">{a.message}</p>
                {a.predicted_impact_minutes !== undefined && (
                  <p className="text-xs text-rail-amber mt-1 font-mono">Predicted impact: +{a.predicted_impact_minutes} min</p>
                )}
                <p className="text-[11px] text-gray-600 mt-2 font-mono">{new Date(a.created_at).toLocaleString()}</p>
              </div>
              {!a.is_acknowledged && (
                <button onClick={() => acknowledge(a.id)} className="btn-secondary btn-sm shrink-0">
                  <CheckCheck className="h-3.5 w-3.5" /> Acknowledge
                </button>
              )}
            </div>
          ))}
        </div>
      )}

      <div className="card px-4 py-3">
        <p className="text-xs text-gray-500">
          Alerts are generated by the backend intelligence engine (extended halts, congestion, weather risk, delay propagation).
          This center only displays alerts the backend has actually produced.
        </p>
      </div>
    </div>
  );
}